[package]
name = "azurite_compiler"
version = "0.1.0"
edition = "2021"

[features]
afl = []

[dependencies]
azurite_common = { path = "../azurite_common" }
azurite_archiver = { path = "../crates/azurite_archiver" }
colored = "*"
unicode-segmentation = "*"
slotmap = "*"