[package]
name = "azurite_compiler"
version = "0.1.0"
edition = "2021"

[features]
readable = []

[dependencies]
azurite_common = { path = "../azurite_common" }
colored = "*"
zip = { version = "0.6.4", default-features = false }
unicode-segmentation = "*"
slotmap = "*"